-- AlterTable
ALTER TABLE "license_configurations" ADD COLUMN     "animations" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "brandWatermark" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "buttonStyle" TEXT NOT NULL DEFAULT 'filled',
ADD COLUMN     "cardBackgroundColor" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "cardStyle" TEXT NOT NULL DEFAULT 'modern',
ADD COLUMN     "compactMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "customCSS" TEXT,
ADD COLUMN     "dashboardLayout" TEXT NOT NULL DEFAULT 'grid',
ADD COLUMN     "favicon" TEXT,
ADD COLUMN     "fontSize" TEXT NOT NULL DEFAULT '14px',
ADD COLUMN     "fontWeight" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN     "glassEffect" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "gradientBackgrounds" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "highContrastMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hoverEffects" TEXT NOT NULL DEFAULT 'subtle',
ADD COLUMN     "largeTextMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "modalStyle" TEXT NOT NULL DEFAULT 'centered',
ADD COLUMN     "navbarCollapsible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "navbarStyle" TEXT NOT NULL DEFAULT 'modern',
ADD COLUMN     "reducedMotion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "responsiveMode" TEXT NOT NULL DEFAULT 'auto',
ADD COLUMN     "shadowIntensity" TEXT NOT NULL DEFAULT 'medium',
ADD COLUMN     "showBreadcrumbs" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showModuleBadges" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showModuleIcons" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showQuickActions" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "splashScreen" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tableStyle" TEXT NOT NULL DEFAULT 'modern',
ADD COLUMN     "textMutedColor" TEXT NOT NULL DEFAULT '#6B7280',
ADD COLUMN     "widgetSizes" TEXT NOT NULL DEFAULT 'mixed';
