/**
 * Shared BI workflow constants + derived UI fields.
 * Single source of truth for request/payment statuses, event types,
 * timeline steps and progress percentages (plan refinements #12/#13).
 */

const REQUEST_STATUS = Object.freeze({
  PENDING_REVIEW: 'PENDING_REVIEW',
  REQUEST_INFO: 'REQUEST_INFO',
  APPROVED: 'APPROVED',
  PROCESSING_ETL: 'PROCESSING_ETL',
  DATA_REVIEW: 'DATA_REVIEW',
  GENERATING_DASHBOARD: 'GENERATING_DASHBOARD',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  PUBLISHED: 'PUBLISHED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

const PAYMENT_STATUS = Object.freeze({
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

const VALID_REQUEST_STATUSES = Object.values(REQUEST_STATUS);
const VALID_PAYMENT_STATUSES = Object.values(PAYMENT_STATUS);

/** Statuses where the client UI auto-polls for progress (refinement #6). */
const ACTIVE_REQUEST_STATUSES = Object.freeze([
  REQUEST_STATUS.PROCESSING_ETL,
  REQUEST_STATUS.DATA_REVIEW,
  REQUEST_STATUS.GENERATING_DASHBOARD,
]);

const TERMINAL_REQUEST_STATUSES = Object.freeze([
  REQUEST_STATUS.REJECTED,
  REQUEST_STATUS.CANCELLED,
  REQUEST_STATUS.COMPLETED,
]);

const EVENT_TYPES = Object.freeze({
  REQUEST_CREATED: 'REQUEST_CREATED',
  ZIP_UPLOADED: 'ZIP_UPLOADED',
  ZIP_VALIDATED: 'ZIP_VALIDATED',
  ZIP_INVALID: 'ZIP_INVALID',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  REQUEST_APPROVED: 'REQUEST_APPROVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_INFO_REQUESTED: 'REQUEST_INFO_REQUESTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  ETL_STARTED: 'ETL_STARTED',
  ETL_COMPLETED: 'ETL_COMPLETED',
  ETL_FAILED: 'ETL_FAILED',
  DASHBOARD_GENERATED: 'DASHBOARD_GENERATED',
  DASHBOARD_PUBLISHED: 'DASHBOARD_PUBLISHED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
});

const NOTIF_TYPES = Object.freeze({
  REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
  NEW_REQUEST: 'NEW_REQUEST',
  ZIP_UPLOADED: 'ZIP_UPLOADED',
  ZIP_VALIDATED: 'ZIP_VALIDATED',
  ZIP_INVALID: 'ZIP_INVALID',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  REQUEST_APPROVED: 'REQUEST_APPROVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_INFO: 'REQUEST_INFO',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  ETL_STARTED: 'ETL_STARTED',
  ETL_COMPLETED: 'ETL_COMPLETED',
  ETL_FAILED: 'ETL_FAILED',
  DASHBOARD_GENERATED: 'DASHBOARD_GENERATED',
  DASHBOARD_PUBLISHED: 'DASHBOARD_PUBLISHED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
});

/** Client timeline steps (1..7) — backend-computed, UI renders verbatim. */
const STEPS = Object.freeze([
  { step: 1, key: 'REQUEST_CREATED', label: 'Demande envoyée' },
  { step: 2, key: 'APPROVED', label: 'Approuvée' },
  { step: 3, key: 'PROCESSING_ETL', label: 'Traitement des données' },
  { step: 4, key: 'DATA_REVIEW', label: 'Révision des données' },
  { step: 5, key: 'GENERATING_DASHBOARD', label: 'Génération du tableau de bord' },
  { step: 6, key: 'READY_FOR_REVIEW', label: 'Tableau de bord prêt' },
  { step: 7, key: 'PUBLISHED', label: 'Publié' },
]);

const STEP_BY_STATUS = Object.freeze({
  [REQUEST_STATUS.PENDING_REVIEW]: 1,
  [REQUEST_STATUS.REQUEST_INFO]: 1,
  [REQUEST_STATUS.APPROVED]: 2,
  [REQUEST_STATUS.PROCESSING_ETL]: 3,
  [REQUEST_STATUS.DATA_REVIEW]: 4,
  [REQUEST_STATUS.GENERATING_DASHBOARD]: 5,
  [REQUEST_STATUS.READY_FOR_REVIEW]: 6,
  [REQUEST_STATUS.PUBLISHED]: 7,
  [REQUEST_STATUS.COMPLETED]: 7,
});

const PROGRESS_BY_STATUS = Object.freeze({
  [REQUEST_STATUS.PENDING_REVIEW]: 10,
  [REQUEST_STATUS.REQUEST_INFO]: 10,
  [REQUEST_STATUS.APPROVED]: 25,
  [REQUEST_STATUS.PROCESSING_ETL]: 40,
  [REQUEST_STATUS.DATA_REVIEW]: 55,
  [REQUEST_STATUS.GENERATING_DASHBOARD]: 70,
  [REQUEST_STATUS.READY_FOR_REVIEW]: 85,
  [REQUEST_STATUS.PUBLISHED]: 95,
  [REQUEST_STATUS.COMPLETED]: 100,
});

function getCurrentStep(status) {
  return STEP_BY_STATUS[status] ?? null;
}

function getProgressPercent(status) {
  return PROGRESS_BY_STATUS[status] ?? null;
}

function isActiveStatus(status) {
  return ACTIVE_REQUEST_STATUSES.includes(status);
}

function isTerminalStatus(status) {
  return TERMINAL_REQUEST_STATUSES.includes(status);
}

module.exports = {
  REQUEST_STATUS,
  PAYMENT_STATUS,
  VALID_REQUEST_STATUSES,
  VALID_PAYMENT_STATUSES,
  ACTIVE_REQUEST_STATUSES,
  TERMINAL_REQUEST_STATUSES,
  EVENT_TYPES,
  NOTIF_TYPES,
  STEPS,
  getCurrentStep,
  getProgressPercent,
  isActiveStatus,
  isTerminalStatus,
};
