/**
 * Electron Preload Script
 * Auto-generated by POS Generator
 */

const { contextBridge, ipcRenderer } = require('electron');

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld('electronAPI', {
  // Database operations
  database: {
    query: (sql, params) => ipcRenderer.invoke('database:query', sql, params),
    execute: (sql, params) => ipcRenderer.invoke('database:execute', sql, params),
    transaction: (queries) => ipcRenderer.invoke('database:transaction', queries)
  },

  // License operations
  license: {
    validate: () => ipcRenderer.invoke('license:validate'),
    getInfo: () => ipcRenderer.invoke('license:getInfo'),
    checkExpiry: () => ipcRenderer.invoke('license:checkExpiry')
  },

  // Window operations
  window: {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close'),
    isMaximized: () => ipcRenderer.invoke('window:isMaximized')
  },

  // File operations
  file: {
    selectDirectory: () => ipcRenderer.invoke('file:selectDirectory'),
    selectFile: (filters) => ipcRenderer.invoke('file:selectFile', filters),
    saveFile: (data, filename) => ipcRenderer.invoke('file:saveFile', data, filename)
  },

  // Settings
  settings: {
    get: (key) => ipcRenderer.invoke('settings:get', key),
    set: (key, value) => ipcRenderer.invoke('settings:set', key, value),
    getAll: () => ipcRenderer.invoke('settings:getAll')
  },

  // Notifications
  notifications: {
    show: (title, body, options) => ipcRenderer.invoke('notifications:show', title, body, options)
  }
});

// Listen for window events
window.addEventListener('DOMContentLoaded', () => {
  console.log('POS Application preload script loaded');
});
